import '../styles/global.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/utils/theme/providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
    // </SessionProvider>
  );
}
